users/urls.py
from django.urls import path, reverse_lazy
from .views import update_profile, community, UserDetailView
from django.contrib.auth import views as auth_views

app_name = "users"
urlpatterns = [
    path(
        "detail/<int:pk>",
        UserDetailView.as_view(template_name="users/profile.html"),
        name="detail",
    ),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="users/logged_out.html"),
        name="logout",
    ),
    path("update/", update_profile, name="update_profile"),
    path("community/", community, name="community"),
    # Password reset views
    path(
        "password_reset",
        auth_views.PasswordResetView.as_view(
            email_template_name="users/password_reset_email.html",
            template_name="users/password_reset.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

users/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token
from PIL import Image
from materials.models import Textbook


def user_picture_path(instance, filename):
    """
    Called when the profile is updated with an image. Supplies the correct
    path to save the user photo.
    """
    return f"user_{instance.id}/{filename}"


class Team(models.Model):
    """
    Students are grouped into teams so members can reach out to one another width
    help on the course material.
    """

    name = models.CharField(max_length=50)
    bio = models.TextField(null=True)

    def __str__(self):
        return self.name


class Enrollment(models.Model):
    """
    This table will hold data related to students enrollment in courses. It will
    hold the current course enrollment, completion status, and past enrollments as
    well any courses they are set as an instructor or mentor on.
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # Currently the foreign key is directly to the textbook but further work should separate
    # concerns so we have a course model that holds the students, mentors and instructors together.
    active_course = models.ForeignKey(
        Textbook, on_delete=models.SET_NULL, blank=True, null=True
    )
    history = models.ManyToManyField(
        Textbook, related_name="course_history", blank=True
    )

    @property
    def completion_status(self):
        """
        Currently this returns the boolean for is the active course complete or not,
        but eventually this will help handle more complex cases.
        """
        return self.active_course.completed(self.user)

    def __str__(self):
        return f"Enrollment for {self.user}"


class Profile(models.Model):
    """
    The profile keeps the student details apart from the auth concerns of the basic
    django user model. Some of the profile fields must be filled in by the course
    runner while others must be completed by the student once they are enrolled.

    These two states of incompletion are represented by the two first bool fields.
    All other fields simply represent the facts that the student may or may not
    want to share.
    """

    course_runner_complete: models.BooleanField = models.BooleanField(default=False)
    user_completed: models.BooleanField = models.BooleanField(default=False)

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField(
        default="default.png", upload_to=user_picture_path
    )

    roles = ((1, "Student"), (2, "Mentor"), (3, "Instructor"))

    role = models.PositiveSmallIntegerField(choices=roles, null=True, blank=True)
    pronouns = models.CharField(max_length=15)
    team = models.ForeignKey("Team", null=True, on_delete=models.SET_NULL)
    buddy = models.ManyToManyField("self", blank=True)

    def save(self, *args, **kwargs) -> None:
        """
        Save the profile as usual but resize the image and save it to the
        appropriate path.
        """
        super().save(*args, **kwargs)

        img = Image.open(self.profile_picture.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.profile_picture.path)

    def get_absolute_url(self) -> str:
        return reverse("users:detail", args=[str(self.user.pk)])


@receiver(post_save, sender=User, dispatch_uid="irrelevant")
def create_student_records(sender, instance, created, **kwargs) -> None:
    """
    Creates a new profile any time a new user is created.
    """
    if created:
        Profile.objects.create(user=instance)
        Enrollment.objects.create(user=instance)
        Token.objects.create(user=instance)

users/forms.py
from django import forms
from .models import Profile


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [
            "role",
            "pronouns",
            "team",
            "buddy",
        ]

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http.response import JsonResponse
from django.urls import path
from .forms import ProfileUpdateForm
from django.contrib import messages
from .models import User
from django.views.generic import DetailView
from materials.views import PrivateAPIViewSet 
from home.views import api_login_required, Token


class UserApiViewSet(PrivateAPIViewSet):
    model = User

    @classmethod
    def get_urlpatterns(cls):
        """
        This can be empty for now.
        """
        return [
            path(
                "",
                cls.as_view({"get": "listing_view"}),
                name="listing",
            ),
        ]

    @api_login_required
    def listing_view(self, request):
        auth_header = request.META.get("HTTP_AUTHORIZATION")
        # If there is no auth, it will be caught by decorator

        _, key = auth_header.split()
        token = Token.objects.get(key=key)
        user = token.user
        user_obj = {
            "id": user.id,
            "pk": user.pk,
            "username": user.username,
            "pronouns": user.profile.pronouns,
            # "buddy": user.profile.buddy, # This needs to be linked up to a detail url
            "profile_complete": user.profile.user_completed, 
        }
        # would like to use drf Response object here, but getting an error.
        return JsonResponse(user_obj)


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User


@login_required
def update_profile(request):
    if request.method == "POST":
        profile_form = ProfileUpdateForm(
            request.POST, request.FILES, instance=request.user
        )
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, "Your profile has been updated!")
            return redirect("users:detail", request.user.pk)

    else:
        profile_form = ProfileUpdateForm(instance=request.user)

    return render(request, "users/update_profile.html", {"profile_form": profile_form})


@login_required
def community(request):
    buddies = request.user.buddy.all()
    announcement = ""
    context = {"buddies": buddies, "announcement": announcement}
    return render(request, "users/community.html", context)

users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

<!-- {% comment %}
	{% include 'courses/css_include.html' %}
	{% include 'courses/js_include.html' %}
    {% endcomment %} -->
	<!-- Required meta tags -->
    <meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<title>Learning Platform</title>
</head>
<body>
	<div class="container">
		<nav class="navbar navbar-expand">
			<div class="container-fluid">
				<a class="navbar-brand" href="{% url 'home' %}">Learning Platform</a>
				<ul class="navbar-nav ms-auto mb-2 mb-lg-0">
					<li class="nav-item">
						<a class="nav-link" href="{% url 'users:community' %}"><i class="bi bi-people-fill"><span class="icon-label">community</span></i></a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'users:detail' request.user.id %}"><i class="bi bi-person-circle"><span class="icon-label">profile</span></i></a>
					</li>
				</ul>
			</div>
		</nav>
		{% if messages %}
	            {% for message in messages %}
	              <div> <!-- bootstrap has a way to handle this with: class="alert alert-{{ message.tags }}" -->
	                Message: {{ message }}
	              </div>
	            {% endfor %}
	          {% endif %}

		{% block content %}
		{% endblock %}
	</div>
	
</body>
</html>

users/templates/users/community.html
{% extends "users/base.html" %}
{% block content %}

<div class="container">
	<div class="row">
		<h1>Your community</h1>
	</div>
	<div class="row">
		<div class="col-lg-12 announcements">
			{{ announcement.text|safe }}
		</div>
	</div>
	<div class="row">
		<div class="col-lg-6 community-feature-box">
			<h2><a href="/forum">Forum</a></h2>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-4 offset-lg-6 col-sm-12 buddy">
      <h2>Your Buddy</h2>
      {% for buddy in user.buddy.all %}
	      <div>
		      <img src="{{ buddy.profile_picture.url }}" width='100px' height='auto'/>
	      </div>
	      <p><a href="{{ buddy.get_absolute_url }}">{{ buddy.first_name }}</a></p>
      {% endfor %}
		</div>
		<div class="col-lg-8 col-sm-12 team">
			<h2>Your team:</h2>
			<h4>{{ user.team.name }}</h4>
			<h5>Team bio:</h5>
			<p>{{ user.team.bio }}</p>

			{% for teammember in user.team.user_set.all %}
				<div>
      		<img src="{{ teammember.profile_picture.url }}" width='100px' height='auto' />
				</div>
				{% if teammember == request.user %}
					<p>YOU</p>
				{% else %}
					<p><a href="{{ teammember.get_absolute_url }}">{{ teammember.first_name }}</a></p>
				{% endif %}
			{% endfor %}
		</div>
	</div>  <!-- end row -->
</div> <!-- end main container -->
{% endblock content %}

users/templates/users/logged_out.html
<!DOCTYPE html>
<html>
<head>
	<title>Learning Platform - Logged out</title>
</head>
<body>
	<p>You have been logged out.</p>
<p><a href="{% url 'users:login' %}">Log in again</a></p>
</body>
</html>

users/templates/users/login.html
<!DOCTYPE html>
<html>
<head>
	<title>Learning Platform - Login</title>
</head>
<body>
	<h1>Welcome to the EII learning platform</h1>
	<form method="POST">
		{% csrf_token %}
		<fieldset>
			<legend>Log In</legend>
			{{ form }}
		</fieldset>
		<button type="submit">Login</button>
	</form>
	<a href="{% url 'users:password_reset' %}">Forgot Password?</a>
</body>
</html>

users/templates/users/password_reset.html
<!DOCTYPE html>
<html>
<head>
	<title>Learning Platform - Reset Password</title>
</head>
<body>
	<h1>Reset your password</h1>
	<form method="POST">
		{% csrf_token %}
		<fieldset>
			<legend>Reset Password</legend>
			{{ form }}
		</fieldset>
		<button type="submit">Login</button>
	</form>
</body>
</html>

users/templates/users/password_reset_complete.html
Your password has been reset.
<a href="{% url 'users:login' %}">Login</a>

users/templates/users/password_reset_confirm.html
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Reset Password</button>
            </div>
        </form>
    </div>

users/templates/users/password_reset_done.html
    <div class="alert alert-info">
        An email has been sent with instructions to reset your password
    </div>

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/profile.html
{% extends "users/base.html" %}
{% block content %}
<div class="container">
	<div class="row profile-card">
		<div class="col-lg-3 col-sm-12">
			<img src="{{ user.profile_picture.url }}" width = '150' height = 'auto'>
		</div>	<!-- end profile image col -->

		<div class="col-lg-9 col-sm-12">
		<h2 class="h-with-update">Your Information</h2> 
		{% if user.pk == request.user.pk %}
			<a href="{% url 'users:update_profile' %}">
					<i class="bi bi-pencil edit"><span class="sr-only">Edit</span></i>
			</a>
		{% endif %}
		<ul>
			<li>{{ user.first_name }} {{ user.last_name }}</li>
			<li>{{ user.get_role_display }}</li>
			<li>Pronouns: {{ user.pronouns }}</li>
			<li>Email: {{ user.email }}</li>
			<li>Team: {{ user.team }}</li>
		</ul>
		</div> <!-- end your info column -->
	</div> <!-- end row -->
	<div class="row">
		<h2>Milestones</h2>
	</div>
	<div class="row">
		<h2>Consent and Sharing</h2>
	</div>
	<p><a href="{% url 'users:logout' %}">Log out</a></p>

</div>
{% endblock content %}

users/templates/users/update_profile.html
{% extends "users/base.html" %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <fieldset class=>
              <legend>Profile Info</legend>
              {{ profile_form }}
          </fieldset>
          <div>
              <button type="submit">Update</button>
          </div>
      </form>
{% endblock content %}